### PR TITLE
#97: webpack script could be nicer in the final project (closes #97)

### LINKED ISSUE #97: webpack script could be nicer in the final project
## requirements
we are currently asking to final projects to use:
```
npm run clean && UV_THREADPOOL_SIZE=20 scriptoni web-build -c ./config
```
where `clean` is typically defined as `rm -rf build/* && mkdir -p build` (note that webpack build output dir is *always* `build`)

Both the `UV_THREADPOOL_SIZE` and the `npm run clean` bits could be handled internally by scriptoni and hidden to the final user

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by ascariandrea**
Closes #97

### tests performed
In the project folder:
- `mkdir build && touch build/a-file.txt`
- `ls build` list `a-file.txt`
-  `npm start`
- `ls build` list nothing ✅ 
- `ls node_modules/react-intl/node_modules` => empty ✅ 
- `ls node_modules/fixed-data-table-2/node_modules` => empty ✅ 
- `ls node_modules/revenge/node_modules` => empty ✅ 

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

**Comment by giogonzo** [comment]
I don't see the THREADPOOL part, did you test this on alinity PRO?

**Comment by ascariandrea** [comment]
@giogonzo I've left the `UV_THREADPOOL_SIZE=20` in the user command, cause I think it will be removed sooner or later

**Comment by giogonzo** [comment]
@ascariandrea and is it actually passed below when invoking webpack? Is it needed? I'm asking because we might remove it completely otherwise

**Comment by veej** [comment]
@ascariandrea do we need to expose a `clean` command for some reason? e.g. `metarpheus clean`

**Comment by ascariandrea** [comment]
@giogonzo I dunno and I didn't find any reference online about its deprecation. I think we need to do some benchmarks to decide.

@veej I checked the alinity-pro `package.json` and the `clean` task is used only by `start` and `build`, that's why I didn't export it

**Pull request merged**
